title: MasteringALM
author: MasteringALM
email: admin@MasteringALM.com # email for form submission, you also have to change it in _js/scripts.js
description: Information on the application lifecycle management. How to move code from source control to production and enable Business deploy and enable software efficiently and safely.
baseurl: "/" # the subpath of your site, e.g. /blog
url: https://www.MasteringALM.github.io
sitename: MasteringALM
contact: admin@MasteringALM.com
contactPhone: 727-537-6507
twitter_username: MasteringMLM
github_username: MasteringMLM 
facebook_username: MasteringMLM
linkedin_username: MasteringMLM
facebook_username: MasteringMLM


#disqus:
#  shortname: masteringmlm # to enable comments replace with your_disqus_shortname


# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
#theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
#permalink: /blog/:year/:month/:day/:title
sass:
    style: compressed
compress_html:
  clippings: all

plugins:

# Includes an icon in the footer for each user name you enter
